export enum ProductTransactionState {
    NEW='NEW',

    WAITING_STORE = 'WAITING_STORE',

    WAITING_SHIPPER = 'WAITING_SHIPPER',

    SHIPPER_PROCESSING= 'SHIPPER_PROCESSING',

    SHIPPER_COMPLETE = 'SHIPPER_COMPLETE',

    ALL_COMPLETE = 'ALL_COMPLETE',

    CANCEL = CANCEL
}